apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-nodeport
  namespace: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    nodePort: 32432
  selector:
    app: postgres
  sessionAffinity: None
  type: NodePort
