apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus
  namespace: nexus
spec:
  ports:
  - name: nexusprivate
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: nexushttp
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: nexusregistry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP
