apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: postgres
spec:  
  serviceName: postgres

  replicas: 1 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: TZ
          value: "Europe/Luxembourg"
        - name: POSTGRES_PASSWORD
          value: OcQBJrUEvCgbId65qoAMdqDkT91t7Sk3wq 
        image: postgres:13.3

        imagePullPolicy: IfNotPresent
        name: postgres
        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-volume
          subPath: postgres
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres

