apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/goeland/data/postgres"
