apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/ingress.class: "haproxy"
  name: sonarqube
  namespace: sonarqube 
spec:
  rules:
  - host: sonarqube.ebrc.com
    http:
      paths:
      - backend:
          service:
            name: sonarqube
            port:
              number: 9000
        path: /
        pathType: ImplementationSpecific
 
  
  tls:
  - hosts:
    - sonarqube.ebrc.com
    secretName: goeland.castanos.fr
