apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
  namespace: nexus
spec:
  selector:
    matchLabels:
      type: "nexus"
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
