apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      type: "postgres"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
