apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
