apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      type: "sonarqube"
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
